<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--    <parent>-->
<!--        <groupId>org.springframework.boot</groupId>-->
<!--        <artifactId>spring-boot-starter-parent</artifactId>-->
<!--        <version>3.3.1</version>-->
<!--        <relativePath/> &lt;!&ndash; lookup parent from repository &ndash;&gt;-->
<!--    </parent>-->
    <groupId>jmaster.io</groupId>
    <artifactId>rental-microservice</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>rental_microservice</name>
    <packaging>pom</packaging>
    <description>Microservice project for renting items</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <modules>
        <module>gatewayservice</module>
        <module>accountservice</module>
        <module>authenticationservice</module>
        <module>itemservice</module>
        <module>configservice</module>
        <module>discoveryservice</module>
        <module>notificationservice</module>
        <module>statisticservice</module>
        <module>monitoradmin</module>
    </modules>
</project>
