spring.application.name=auth-service
# JWT config
#bezkoder.app.jwtSecret=i+nR7sKGUx1c9vtjp/9YuCDy2nsrYqU6jj/ID7uSu/A5CcLGdj5rJgG2oIsRNJfJo0vC9N9SD1E0+UzPm71+hA==

# 15 minutes = 900000 ms
bezkoder.app.jwtExpirationMs=900000  

# 7 days = 604800000 ms
bezkoder.app.refreshExpirationMs=604800000


spring.config.import=configserver:http://localhost:8888
#This file is the entrypoint for spring to know where to look for the configuration file and hold the initial configuration
spring.cloud.config.fail-fast=true
#the service will not run if it can't reach the config-service

# # Local OTLP Logging Overrides
# management.otlp.logs.endpoint=${OTEL_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
# management.otlp.logging.endpoint=${OTEL_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
# management.otlp.logs.export.enabled=true

# Debugging OpenTelemetry and Logging Auto-Configuration
logging.level.org.springframework.boot.opentelemetry=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure.logging=DEBUG
logging.level.org.example.commonlib=DEBUG

