spring.application.name=payment-service
server.port=8084
#spring.config.import=file:/.env, add this to import from file system
spring.config.import=configserver:http://localhost:8888
PAYPAL_CLIENT_ID=AfJY4_LRanPR1sgqBGh9AgPYjTIqxgDfBqxTb_kTrJNeij9ZpR-uY_yfQhWGsu0aKkrMx0COKMPu8FC4
PAYPAL_CLIENT_SECRET=EPTCcslai8E83rcFw9s_UhxiyvT1a1PM-9Ct9myKKygbZWgF0c4vbngolM2uftk2xMXHWmJWVvRs1nYJ

spring.datasource.url=jdbc:mysql://localhost:3306/payment_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=nam
spring.datasource.password=nam123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
