# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # MYSQL_DATABASE: 
      MYSQL_USER: nam
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rental_network

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    restart: always
    ports:
      - "5050:8080"
    networks:
      - rental_network
    depends_on:
      - mysql
    

  redis:
    image: redis:7.0-alpine
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight_ui
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - rental_network
    depends_on:
      - redis

volumes:
  mysql_data:
  redis_data:
  redis_insight_data:

networks:
  rental_network:
    driver: bridge