server.port=8081
#Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=6000
# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=nam
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
bezkoder.app.jwtSecret=eZgDADp8dsMJsMerDXgnuzGdwdq9A9XGz9SLMry+pqM=
# Access token: 2 ti?ng
bezkoder.app.jwtExpirationMs=60000

# Refresh token: 7 ng�y
bezkoder.app.refreshExpirationMs=604800000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


